name: Test

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Run tests
    runs-on: macOS-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Test
      run: xcodebuild -project CameraController.xcworkspace -scheme CameraController -sdk macos test | xcpretty